import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import wiki from './wiki.config.json';

const config: Config = {
  title: wiki.title,
  tagline: wiki.tagline,
  favicon: 'img/favicon.png',

  url: wiki.url,
  baseUrl: '/',

  organizationName: wiki.organizationName,
  projectName: wiki.projectName,

  onBrokenLinks: 'throw',

  // Rust toolchain (Rspack + SWC) instead of webpack + Babel. Cuts cold build
  // time roughly in half. Safe because the custom plugins use only getThemePath
  // (no configureWebpack / Babel hooks) and there are no custom Babel plugins.
  // Requires @docusaurus/faster (already a devDependency).
  // (On Docusaurus < 3.10 this flag is named `experimental_faster`.)
  future: {
    v4: true,
    faster: true,
  },

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  headTags: [
    // Docusaurus emits only the single `favicon` link, so everything an iOS home
    // screen or an install prompt needs is declared here. The manifest is
    // written at build time by plugins/manifest-plugin, and the edge gate has to
    // exempt `.webmanifest` separately from `.json`: see middleware.ts.
    { tagName: 'link', attributes: { rel: 'apple-touch-icon', sizes: '180x180', href: '/img/apple-touch-icon.png' } },
    { tagName: 'link', attributes: { rel: 'icon', type: 'image/png', sizes: '192x192', href: '/img/icon-192.png' } },
    { tagName: 'link', attributes: { rel: 'icon', type: 'image/png', sizes: '512x512', href: '/img/icon-512.png' } },
    { tagName: 'link', attributes: { rel: 'manifest', href: '/manifest.webmanifest' } },
    {
      tagName: 'meta',
      attributes: {
        name: 'theme-color',
        content: (wiki as { og?: { bg?: string } }).og?.bg ?? '#ffffff',
      },
    },
    ...(wiki.noindex
      ? [{ tagName: 'meta', attributes: { name: 'robots', content: 'noindex, nofollow' } }]
      : []),
  ],

  plugins: [
    './plugins/search-plugin',
    './plugins/creation-date-plugin',
    // Per-page social share cards: every page without a frontmatter `image:`
    // hero gets a branded og:image card generated at build time. Brand tokens
    // come from the optional `og` block in wiki.config.json.
    './plugins/manifest-plugin',
    ['./plugins/og-image-plugin', (wiki as { og?: Record<string, string> }).og ?? {}],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          editUrl: undefined,
          showLastUpdateTime: false,
          showLastUpdateAuthor: false,
          // Filter folder index docs out of every autogenerated section.
          // Each category in sidebars.ts links to its section's index via
          // `link: { type: 'doc', id: 'X/index' }`, so the category header
          // IS the navigation to the index. Without this filter, Docusaurus
          // 3.10 also includes the index as a duplicate child entry.
          sidebarItemsGenerator: async ({defaultSidebarItemsGenerator, ...args}) => {
            const items = await defaultSidebarItemsGenerator(args);
            const stripIndex = (list: any[]): any[] =>
              list
                .filter((item) => !(item.type === 'doc' && typeof item.id === 'string' && item.id.endsWith('/index')))
                .map((item) =>
                  item.type === 'category' && Array.isArray(item.items)
                    ? {...item, items: stripIndex(item.items)}
                    : item
                );
            return stripIndex(items);
          },
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
        sitemap: wiki.noindex ? false : undefined,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: undefined,

    // Docusaurus already emits og:title/description/url/locale/image and the
    // twitter pair. These are the ones it does NOT, and their absence stays
    // invisible until a card renders wrong somewhere. Every card this template
    // generates is 1200x630, so the dimensions are true for all of them.
    metadata: [
      { property: 'og:type', content: 'article' },
      { property: 'og:site_name', content: wiki.title },
      { property: 'og:image:width', content: '1200' },
      { property: 'og:image:height', content: '630' },
    ],
    navbar: {
      title: wiki.title,
      logo: undefined,
      items: [],
    },
    footer: {
      style: 'light',
      links: [],
      copyright: wiki.copyright,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
    colorMode: {
      defaultMode: 'light',
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
